import assert from 'node:assert/strict';
import { getDb } from '../functions/src/adminApp';
import { executeWorkOrderCycle } from '../functions/src/workOrderCycle';
import { assertLegacyReportOrder } from '../functions/src/workOrderCycleBoundary';
import { processProductionReportBackground } from '../functions/src/productionReportBackground';
import { createProductionReportFastHandler } from '../functions/src/productionReportFast';
import { applyProductionReportInventoryInternal, reverseProductionReportInventory } from '../functions/src/productionReportInventory';

if (!process.env.GCLOUD_PROJECT?.startsWith('demo-') || !/^(127\.0\.0\.1|localhost):\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST || '')) throw new Error('Local demo emulator required');
const db = getDb(); const suffix = Date.now().toString(); const tenantId = `safety-${suffix}`; const orderId = `safety-order-${suffix}`;
const users = { manager: { 'workOrders.create': true, 'workOrders.approve': true }, supervisor: { 'workOrders.execute': true }, quality: { 'workOrders.assignInspectors': true }, inspector1: { 'workOrders.inspect': true }, inspector2: { 'workOrders.inspect': true }, unassigned: { 'workOrders.inspect': true } };
const uid = (name: keyof typeof users) => `${tenantId}-${name}`;
for (const [name, permissions] of Object.entries(users)) {
  const person = `${tenantId}-${name}`;
  await db.doc(`roles/${person}`).set({ tenantId, permissions });
  await db.doc(`users/${person}`).set({ tenantId, roleId: person, isActive: true, displayName: name });
}
await db.doc(`products/${tenantId}`).set({ tenantId, isActive: true });
await db.doc(`production_lines/${tenantId}`).set({ tenantId, isActive: true });
await db.doc(`employees/${tenantId}`).set({ tenantId, isActive: true });
const call = (person: keyof typeof users, action: Parameters<typeof executeWorkOrderCycle>[1]['action'], payload: Record<string, unknown> = {}, requestId: string = crypto.randomUUID()) => executeWorkOrderCycle(uid(person), { orderId, action, payload, requestId });
await call('manager', 'prepare', { productId: tenantId, lineId: tenantId, supervisorUid: uid('supervisor'), quantity: 100, workOrderNumber: 'SAFETY', slots: [{ date: '2026-09-12', startTime: '08:00', endTime: '09:00', targetQuantity: 100 }] });
await call('quality', 'defineQualityReport', { qualityReportTemplate: [{ id: 'weight', label: 'وزن', inputType: 'number', required: true, minValue: 0, maxValue: 10 }, { id: 'note', label: 'وصف', inputType: 'text', required: false }] });
await call('quality', 'assignInspectors', { inspectorUids: [uid('inspector1'), uid('inspector2')] });
await call('manager', 'approve');
await call('supervisor', 'assignWorkers', { workerIds: [tenantId] });
await call('supervisor', 'start', { slotId: 'hour-001' });
await call('supervisor', 'submit', { slotId: 'hour-001', actualQuantity: 100, rejectedQuantity: 0 });
const results = [{ checkId: 'weight', value: 0 }];
await assert.rejects(call('unassigned', 'submitQualityReport', { slotId: 'hour-001', qualityResults: results }), 'An unassigned inspector cannot write quality results');
await assert.rejects(call('unassigned', 'claimQualityInspection', { slotId: 'hour-001' }));
const slotRef = db.doc(`work_orders/${orderId}/hourly_slots/hour-001`);
const race = await Promise.allSettled([call('inspector1', 'claimQualityInspection', { slotId: 'hour-001' }), call('inspector2', 'claimQualityInspection', { slotId: 'hour-001' })]);
assert.equal(race.filter(row => row.status === 'fulfilled').length, 1);
let claim = (await slotRef.get()).data()!.qualityClaim;
const winner = claim.uid === uid('inspector1') ? 'inspector1' : 'inspector2';
const other = winner === 'inspector1' ? 'inspector2' : 'inspector1';
const payload = { slotId: 'hour-001', claimId: claim.id, inspectedQuantity: 60, acceptedQuantity: 60, rejectedQuantity: 0, qualityResults: results };
await assert.rejects(call(other, 'submitQualityReport', payload));
for (const qualityResults of [[], [{ checkId: 'unknown', value: 0 }], [{ checkId: 'weight', value: '0' }], [{ checkId: 'weight', value: 11 }], [...results, ...results]]) await assert.rejects(call(winner, 'submitQualityReport', { ...payload, qualityResults }));
await assert.rejects(call(winner, 'submitQualityReport', { ...payload, acceptedQuantity: 61 }));
await call(winner, 'submitQualityReport', payload, 'part-60');
await call(winner, 'submitQualityReport', payload, 'part-60');
assert.equal((await slotRef.get()).data()!.inspectedQuantity, 60);
const contribution = (await slotRef.collection('quality_contributions').doc(claim.id).get()).data();
assert.equal(contribution?.results[0].value, 0, 'Zero is valid');
assert.equal(contribution?.results[0].label, 'وزن', 'Server owns labels');
await assert.rejects(call(winner, 'submitQualityReport', payload, 'duplicate-new-id'));
await call(other, 'claimQualityInspection', { slotId: 'hour-001' });
claim = (await slotRef.get()).data()!.qualityClaim;
await call('quality', 'assignInspectors', { inspectorUids: [uid(winner)] });
await assert.rejects(call(other, 'submitQualityReport', { ...payload, claimId: claim.id, inspectedQuantity: 40, acceptedQuantity: 40 }));
await assert.rejects(call('quality', 'releaseQualityInspection', { slotId: 'hour-001', claimId: claim.id, reason: '' }));
await call('quality', 'releaseQualityInspection', { slotId: 'hour-001', claimId: claim.id, reason: 'إعادة التكليف' });
await call('quality', 'assignInspectors', { inspectorUids: [uid(winner), uid(other)] });
await call(other, 'claimQualityInspection', { slotId: 'hour-001' });
const currentClaim = (await slotRef.get()).data()!.qualityClaim;
await assert.rejects(call('quality', 'releaseQualityInspection', { slotId: 'hour-001', claimId: claim.id, reason: 'حجز قديم' }));
await assert.rejects(call(other, 'submitQualityReport', { ...payload, claimId: currentClaim.id, inspectedQuantity: 41, acceptedQuantity: 41 }));
await call(other, 'submitQualityReport', { ...payload, claimId: currentClaim.id, inspectedQuantity: 40, acceptedQuantity: 38, rejectedQuantity: 2 });
assert.equal((await slotRef.get()).data()!.inspectedQuantity, 100);
assert.equal((await slotRef.get()).data()!.inspectedAcceptedQuantity, 98);
assert.equal((await slotRef.collection('quality_contributions').get()).size, 2);
assert.deepEqual((await slotRef.collection('quality_contributions').doc(payload.claimId).get()).data(), contribution);
assert.equal((await db.doc(`work_orders/${orderId}`).get()).data()!.approvedAcceptedQuantity, 0);
await assert.rejects(call(winner, 'claimQualityInspection', { slotId: 'hour-001' }));
await assert.rejects(assertLegacyReportOrder({ workOrderId: orderId }));
const legacyId = `legacy-${suffix}`;
await db.doc(`work_orders/${legacyId}`).set({ tenantId, lineId: tenantId, status: 'pending' });
await assertLegacyReportOrder({ workOrderId: legacyId });
await assertLegacyReportOrder({});
const reportId = `blocked-report-${suffix}`;
await db.doc(`production_reports/${reportId}`).set({ tenantId, workOrderId: orderId, processingState: 'pending', quantityProduced: 999 });
const beforeOrder = (await db.doc(`work_orders/${orderId}`).get()).data();
await assert.rejects(processProductionReportBackground(reportId));
assert.deepEqual((await db.doc(`work_orders/${orderId}`).get()).data(), beforeOrder);
assert.equal((await db.doc(`production_reports/${reportId}`).get()).data()?.processingState, 'pending', 'Blocked before side effects');
await db.doc(`roles/${uid('manager')}`).set({ permissions: { ...users.manager, 'reports.create': true, 'reports.edit': true } }, { merge: true });
const boundaryError = (error: unknown) => (error as Error).message.includes('الدورة الجديدة');
await assert.rejects(applyProductionReportInventoryInternal(uid('manager'), reportId), boundaryError);
await assert.rejects(reverseProductionReportInventory.run({ auth: { uid: uid('manager') }, data: { reportId } } as any), boundaryError);
const reportInput = { employeeId: tenantId, productId: tenantId, lineId: tenantId, date: '2026-09-12', quantityProduced: 5, workersCount: 1, workHours: 1, workOrderId: orderId };
await assert.rejects(createProductionReportFastHandler({ auth: { uid: uid('manager') }, data: { report: reportInput } } as any), boundaryError);
await db.doc(`work_orders/${legacyId}`).update({ supervisorId: tenantId, productId: tenantId });
await createProductionReportFastHandler({ auth: { uid: uid('manager') }, data: { report: { ...reportInput, workOrderId: legacyId } } } as any);
console.log('PASS: assignment, exclusive claim, immutable 60+40 contributions, revocation, manager release, validation, replay and legacy boundary');
