import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Archive,
  ArrowLeftRight,
  BarChart3,
  Bus,
  CalendarDays,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  DollarSign,
  Factory,
  FileText,
  Fingerprint,
  FlaskConical,
  GitBranch,
  Hammer,
  Landmark,
  Link,
  Package,
  PlusCircle,
  Printer,
  ReceiptText,
  RefreshCw,
  Scale,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Table,
  Upload,
  User,
  UserCheck,
  UserCog,
  Users,
  Wallet,
  Warehouse,
  Wrench,
  Zap,
} from 'lucide-react';

const MENU_ICON_MAP: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_tree: GitBranch,
  add_circle: PlusCircle,
  admin_panel_settings: Shield,
  alt_route: GitBranch,
  analytics: BarChart3,
  assignment: ClipboardList,
  assignment_ind: UserCheck,
  badge: Users,
  bar_chart: BarChart3,
  beach_access: User,
  bolt: Zap,
  build: Wrench,
  category: Package,
  construction: Hammer,
  dashboard: BarChart3,
  directions_bus: Bus,
  engineering: UserCog,
  event_note: CalendarDays,
  fact_check: CheckSquare,
  fingerprint: Fingerprint,
  group_work: Link,
  groups: Users,
  home: BarChart3,
  inventory: Archive,
  inventory_2: Package,
  manage_accounts: UserCog,
  monitoring: Activity,
  payments: Wallet,
  person: User,
  precision_manufacturing: Factory,
  price_check: DollarSign,
  print: Printer,
  receipt_long: ReceiptText,
  rule: Scale,
  science: FlaskConical,
  settings: Settings,
  shield: Shield,
  space_dashboard: BarChart3,
  swap_horiz: ArrowLeftRight,
  sync: RefreshCw,
  sync_alt: ArrowLeftRight,
  table_view: Table,
  task_alt: CheckCircle2,
  tune: Settings2,
  upload: Upload,
  verified: ShieldCheck,
  verified_user: ShieldCheck,
  warehouse: Warehouse,
};

export function resolveMenuIcon(name?: string): LucideIcon {
  if (!name) return FileText;
  return MENU_ICON_MAP[name] ?? FileText;
}
