import type { ReportPrintRow } from '../components/ProductionReportPrint';

/** Shared demo row for print / WhatsApp share card previews (settings + export lab). */
export const PRINT_PREVIEW_SAMPLE_ROW: ReportPrintRow = {
  reportId: 'preview-1',
  reportCode: 'PR-000001',
  date: '2026-03-15',
  lineName: 'خط إنتاج 1',
  productName: 'راديو RX-606',
  employeeName: 'مشرف تجريبي',
  quantityProduced: 1200,
  wasteQuantity: 35,
  workersCount: 12,
  workersProductionCount: 6,
  workersPackagingCount: 3,
  workersQualityCount: 2,
  workersMaintenanceCount: 1,
  workersExternalCount: 0,
  workHours: 8,
  workOrderNumber: 'WO-0001',
  costPerUnit: 2.35,
};

export const PRINT_PREVIEW_SAMPLE_ROWS: ReportPrintRow[] = [
  PRINT_PREVIEW_SAMPLE_ROW,
  {
    reportId: 'preview-2',
    reportCode: 'PR-000002',
    date: '2026-03-15',
    lineName: 'خط 2',
    productName: 'منتج B',
    employeeName: 'سعيد علي',
    quantityProduced: 950,
    wasteQuantity: 20,
    workersCount: 10,
    workersProductionCount: 5,
    workersPackagingCount: 3,
    workersQualityCount: 1,
    workersMaintenanceCount: 1,
    workersExternalCount: 0,
    workHours: 8,
  },
  {
    reportId: 'preview-3',
    reportCode: 'PR-000003',
    date: '2026-03-15',
    lineName: 'خط 3',
    productName: 'منتج C',
    employeeName: 'خالد حسن',
    quantityProduced: 800,
    wasteQuantity: 15,
    workersCount: 8,
    workersProductionCount: 4,
    workersPackagingCount: 2,
    workersQualityCount: 1,
    workersMaintenanceCount: 1,
    workersExternalCount: 0,
    workHours: 7.5,
  },
];
