export const MODAL_KEYS = {
  DAILY_WELCOME: 'system.dailyWelcome',
  REPORTS_CREATE: 'reports.create',
  REPORTS_IMPORT: 'reports.import',
  PRODUCTION_PLAN_FOLLOW_UP_CREATE: 'productionPlans.followUp.create',
  WORK_ORDERS_CREATE: 'workOrders.create',
  PRODUCTS_CREATE: 'products.create',
  LINES_CREATE: 'lines.create',
  EMPLOYEES_CREATE: 'employees.create',
  ORGANIZATION_CREATE: 'organization.create',
  VEHICLES_CREATE: 'vehicles.create',
  COST_CENTERS_CREATE: 'costCenters.create',
  PRODUCT_MATERIALS_CREATE: 'products.materials.create',
  EMPLOYEE_ALLOWANCE_CREATE: 'employees.allowance.create',
  EMPLOYEE_DEDUCTION_CREATE: 'employees.deduction.create',
  INVENTORY_IMPORT_IN_BY_CODE: 'inventory.movements.importInByCode',
  PRODUCTION_PLANS_IMPORT: 'productionPlans.import',
  INVENTORY_WAREHOUSES_CREATE: 'inventory.warehouses.create',
  INVENTORY_RAW_MATERIALS_CREATE: 'inventory.rawMaterials.create',
  INVENTORY_RAW_MATERIALS_IMPORT: 'inventory.rawMaterials.import',
  SYSTEM_ROLES_CREATE: 'system.roles.create',
  SYSTEM_USERS_MANAGE: 'system.users.manage',
  SYSTEM_USERS_CREATE: 'system.users.create',
  SYSTEM_USERS_IMPORT: 'system.users.import',
  PRODUCTION_SUPERVISOR_ASSIGNMENT_HISTORY: 'production.supervisorAssignment.history',
  ATTENDANCE_SHIFT_RULES: 'attendance.shiftRules',
  ATTENDANCE_SIGNATURE_FIX: 'attendance.signatureFix',
} as const;

export type ModalKey = (typeof MODAL_KEYS)[keyof typeof MODAL_KEYS];
